language: ruby
rvm:
  - ruby-head
  - 3.1
  - 3.0
  - 2.7
  - 2.2
  - 2.1
  - 2.0.0
  - jruby-head
  - jruby-9000
matrix:
  allow_failures:
    - rvm: jruby-head
addons:
  apt:
    packages:
      - libgmp3-dev
