language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - ruby-head
  - 3.1
  - 3.0
  - 2.7
  - 2.2
  - 2.1
  - 2.0.0
  - jruby-9.1
matrix:
  allow_failures:
    - rvm: jruby-head
addons:
  apt:
    packages:
      - libgmp3-dev
